name: Build profiles from CSV/XLSX

on:
  push:
    branches: [ main ]
    paths:
      - "tools/profiles.csv"
      - "tools/profiles.xlsx"
      - "tools/csv2profiles.js"
      - "tools/updateIndex.js"
      - "package.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Generate profiles/*.json from CSV/XLSX
        run: |
          if [ -f tools/profiles.csv ] || [ -f tools/profiles.xlsx ]; then
            node tools/csv2profiles.js
          else
            echo "No CSV/XLSX found under tools/. Skip generation."
          fi

      - name: Build profiles/index.json
        run: node tools/updateIndex.js

      - name: Show changes
        run: |
          git status
          git --no-pager diff --name-only

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profiles/*.json profiles/index.json 2>/dev/null || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update profiles from CSV [skip ci]"
            git push
          fi
